### ISSUE TITLE
RemoteManager_server.cpp compile issues

### ISSUE THREAD

**Issue by kraterrak** [OpenZWave/Thrift4OZW#10]
Hi there.

I'm trying to compile Thrift4OZW on Debian and I've come across the following issue after running    make    :

```
make[1]: Entering directory `/home/cubie/thrift_ozw/open-zwave-read-only/cpp/build'
make[1]: Nothing to be done for `default'.
make[1]: Leaving directory `/home/cubie/thrift_ozw/open-zwave-read-only/cpp/build'
#cd ; make 
g++ -c -DHAVE_INTTYPES_H -DHAVE_NETINET_IN_H -Wall -Wno-format -g -DDEBUG -Werror -O0 -DDEBUG_BOOSTSTOMP   -c Main.cpp -I /usr/local/include/openzwave -I /usr/local/include/openzwave/command_classes/ -I /usr/local/include/openzwave/value_classes/ -I /usr/local/include/openzwave/platform/    -I /usr/local/include/openzwave/platform/unix   -I /usr/local/include/thrift -I /usr/local/include/booststomp -I . -I gen-cpp   
In file included from Main.cpp:392:0:
gen-cpp/RemoteManager_server.cpp: In member function 'virtual void RemoteManagerHandler::SceneGetValues(OpenZWave::SceneGetValuesReturnStruct&, int8_t)':
gen-cpp/RemoteManager_server.cpp:972:82: error: 'class std::vector<OpenZWave::RemoteValueID>' has no member named 'toValueID'
make: *** [Main.o] Error 1
```

I'm not quite sure what is causing this. I have followed all of the instructions in    INSTALL.txt    as closely as possible.

Thanks in advance

**Comment by eflukx** [comment]
Any news on this yet? Seems to be still broken in 112330c
